### ISSUE TITLE
Installation error: package directory 'src/src' does not exist 

### ISSUE THREAD

**Issue by yuchenlin** [iesl/protoqa-evaluator#3]
Hi @mboratko ,

I found that after your latest commits, running `pip install -e protoqa-evaluator` will cause the below error:

```bash
(protoqa) bill@ink-gary:~/protoqa_exps$ pip install -e protoqa-evaluator
Obtaining file:///home/bill/protoqa_exps/protoqa-evaluator
    ERROR: Command errored out with exit status 1:
     command: /home/bill/anaconda3/envs/protoqa/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/bill/protoqa_exps/protoqa-evaluator/setup.py'"'"'; __file__='"'"'/home/bill/protoqa_exps/protoqa-evaluator/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3mf4gm62
         cwd: /home/bill/protoqa_exps/protoqa-evaluator/
    Complete output (9 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info
    writing /tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-3mf4gm62/protoqa_evaluator.egg-info/SOURCES.txt'
    error: package directory 'src/src' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Thanks!

**Comment by yuchenlin** [comment]
The previous version won't have this problem, though.

**Comment by yuchenlin** [comment]
I fixed this by changing ```package_dir={"": "src"},``` to ```package_dir={"src": "src"},``` in the ```setup.py```, so it won't report the error during the installation. 


However, it has the error when importing after installing with the above fix

```python
>>> import protoqa_evaluator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'protoqa_evaluator'
```
Also， when running ```protoqa_evaluator evaluate`` in the terminal:

```bash
(protoqa) bill@ink-gary:~/protoqa_exps$ protoqa_evaluator evaluate
Traceback (most recent call last):
  File "/home/bill/anaconda3/envs/protoqa/bin/protoqa_evaluator", line 8, in <module>
    from protoqa_evaluator.__main__ import main
ModuleNotFoundError: No module named 'protoqa_evaluator'
```

**Comment by mboratko** [comment]
This is fixed in the most recent commit. (Somehow a spurious `__init__.py` file got added to the `src/` directory.)

**Comment by yuchenlin** [comment]
Thanks very much. It works now.
